version: "3.9"


networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1


services:
  app01_pgadmin:
    image: dpage/pgadmin4:5.7
    container_name: app01_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "webbi@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "webbi_pwd"
    volumes:
      - app01:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      backend:
        ipv4_address: 192.168.1.2

  db01_postgres:
    image: postgres:13.3
    container_name: db01_postgres
    environment:
      POSTGRES_DB: "webbi_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Wj24qIiY7lfR"
    volumes:
      - ../database:/docker-entrypoint-initdb.d
      - db01:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      backend:
        ipv4_address: 192.168.1.3


volumes:
  app01:
  db01: